package com.appfactory.aprivatenotesappwithencryptedofflinestoragebackupandremindernotifications;

import java.util.Objects;

/** A persisted entity generated by the AppFactory scaffold. */
public final class Item {
    public final String id;
    public final String title;
    public final String detail;
    public final long createdAt;

    public Item(String id, String title, String detail, long createdAt) {
        this.id = id;
        this.title = title;
        this.detail = detail;
        this.createdAt = createdAt;
    }
    @Override public boolean equals(Object o) {
        if (!(o instanceof Item)) return false;
        return Objects.equals(((Item) o).id, id);
    }
    @Override public int hashCode() { return Objects.hashCode(id); }
}
