plugins {
    id 'com.android.application' version '8.5.2'
}

android {
    namespace 'com.appfactory.aonebuttonhelloworld'
    compileSdk 34

    defaultConfig {
        applicationId 'com.appfactory.aonebuttonhelloworld'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}